# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20200212_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(default='roman_reigns.jpg', upload_to='')),
            ],
        ),
    ]
