# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
